// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfFNmaXs1_Q0duM4VXTvBx2PRcCurSsRM',
    appId: '1:493362261757:web:b9423e85f02041a5a2d894',
    messagingSenderId: '493362261757',
    projectId: 'familykitchen-fe204',
    authDomain: 'familykitchen-fe204.firebaseapp.com',
    storageBucket: 'familykitchen-fe204.appspot.com',
    measurementId: 'G-92F3DFKBSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeOCvwjtWgAqI419HMbj2VRKuEtzP4Jf4',
    appId: '1:493362261757:android:13bb67b1324aa7afa2d894',
    messagingSenderId: '493362261757',
    projectId: 'familykitchen-fe204',
    storageBucket: 'familykitchen-fe204.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYA1uN8n8BrypRvzVbHxc5vpbVy4pWG90',
    appId: '1:493362261757:ios:37823bac987683f4a2d894',
    messagingSenderId: '493362261757',
    projectId: 'familykitchen-fe204',
    storageBucket: 'familykitchen-fe204.appspot.com',
    iosClientId: '493362261757-52o9dsfof88l1kj9q0738gsur1ipsjev.apps.googleusercontent.com',
    iosBundleId: 'com.wonder.zone',
  );
}
